# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Work smarter, not harder
description: > # this means to ignore newlines until "baseurl:"
  <p>Technologie is er om voor jouw te werken. Er zijn zo veel redenen waardoor je gestrest kan raken, maar technologie zou daar niet bij moeten zijn horen.</p>

  <p>Wanneer dit wel het geval is moet je de tools die je gebruikt op een andere manier inzetten.</p>

  <p>“Mag deze app je push notificaties sturen”, dit zijn van die kleine vragen waar de meeste mensen zonder na te denken ja op zeggen, maar deze vraag moet eigenlijk zijn “Mag deze app je op elk moment van de dag storen?”.</p>

  <p>Op deze manier nadenken over welke apps jouw aandacht mogen vragen is waar ik mensen bekent mee wil maken. Een paar kleine aanpassingen in je werkwijze en onderdelen van je werk automatiseren kunnen er voor zorgen dat technologie niet tegen je werken, maar voor je!</p>
tagline: Laat technologie niet tegen, maar voor  je werken.

author: Mitchel van Eijgen
bio: Grafisch ontwerper met een liefde voor technologie.
email: mvaneijgen@gmail.com
phone: 06 38 63 27 35
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://worksmarternotharder.nl" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mvaneijgen
github_username:  mvaneijgen
instagram_username:  mvaneijgen
facebook_username:  mvaneijgen
linkedin_username:  mvaneijgen


repository: mvaneijgen/work-smarter-not-harder
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

collections:
  sections:
    output: false
  steps:
    output: false
  superpowers:
    output: false
    # permalink: /:name

excerpt_separator: ""
